language: r
cache: packages
sudo: false

r:
  - bioc-devel
  - bioc-release

bioc_packages:
  - Biobase
  - GO.db
  - BiocStyle

r_packages:
  - httr
  - progress
  - jsonlite
  - knitr
  - testthat
  - lubridate
  - DT
  - rmarkdown
  - covr
  
after_success:
  - Rscript -e 'library(covr); codecov()'

# print timings (of examples) and sysinfo
after_script:
  - dump_logs_by_extension "timings"
  - dump_sysinfo

notifications:
  email:
    on_success: lg390@cam.ac.uk
    on_failure: lg390@cam.ac.uk

